spdlog/src/sink/rotating_file_sink.rs
Existing documentation of the rotating file sink is too simple and incomprehensive. This PR improves its documentation.
=> Add comprehensive documentation to the rotating file sink

spdlog/benches/compare_with_cpp_spdlog_async.rs, spdlog/benches/spdlog_rs.rs, spdlog/src/error.rs, spdlog/src/lib.rs, spdlog/src/logger.rs
Closes #13.
To avoid confusion with the semantics of `Arc::clone`, I have named the new methods as `fork_xxx`.
=> Allow forking from existing loggers

spdlog/Cargo.toml, spdlog/src/sink/std_stream_sink.rs
https://rustsec.org/advisories/RUSTSEC-2021-0145 details an alignment/unsoundness issue in `atty`, which is solved with the smaller `is-terminal` crate.  This PR changes the dependency!
Tests pass locally - happy to iterate if there are things that could be factored/done better
=> use is-terminal instead of atty dep for RUSTSEC-2021-0145

spdlog/src/record.rs, spdlog/src/source_location.rs, spdlog/tests/log_crate_proxy.rs
Fixes #22.
The problem is that the source location from the `log` crate is an internal type `MaybeStaticStr<'a>` which is like a `Cow<'static, str>`, so that means they are possible to be runtime `&'a str` instead of `&'static str`.
I had left a `None` for the `source_location` inside the proxy since we store location information as `&'static str` so there is no way to store runtime `&'a str` in it unless we change the API.
But reconsider the situation, most crates only use the logging macros from `log` crate instead of constructing something manually, and source location from macros should always be `&'static str`, So we can safely ignore those `&'a str` cases, which should not be a big problem.
=> Retain source location from `log` crate if they are `&'static`

spdlog/Cargo.toml
Updates dependency to the patch version of 0.9.8
[Advisory](https://rustsec.org/advisories/RUSTSEC-2023-0031.html) | mvdnes/spin-rs#148
=> Bump dependency `spin` to v0.9.8 for RUSTSEC-2023-0031

clippy.toml, spdlog/src/error.rs, spdlog/src/formatter/pattern_formatter/pattern/process_id.rs, spdlog/src/formatter/pattern_formatter/pattern/thread_id.rs, spdlog/src/record.rs, spdlog/tests/pattern.rs
Fixes #28, by getting TID during the build of each record and caching it in the thread local to improve performance.
=> Fix `{tid}` incorrectly outputting TID of thread pool in `AsyncPoolSink`

spdlog/src/record.rs
Fixes #31.
Reference from [gettid() of Ubuntu manpage](https://manpages.ubuntu.com/manpages/focal/en/man2/gettid.2.html).
> Library  support  was added  in  glibc  2.30.  (Earlier glibc versions did not provide a wrapper for this system  call, necessitating the use of [syscall](https://manpages.ubuntu.com/manpages/focal/en/man2/syscall.2.html)(2).)
=> Replace `gettid()` with `syscall(SYS_gettid)` for earlier glibc versions

spdlog/src/record.rs
This PR changes the implementation of `fn get_current_tid()` on macOS.
The previous used `pthread_self()` returns an opaque type `pthread_t` with a large value. Instead, `pthread_threadid_np` returns a system-wide unique integral ID of thread in the location specified by `thread_id`.
Note that `pthread_threadid_np` doesn't seem to exist before macOS 10.6 as mentioned from [C++ spdlog comment](https://github.com/gabime/spdlog/blob/7e635fca68d014934b4af8a1cf874f63989352b7/include/spdlog/details/os-inl.h#L363-L364), we can use `pthread_mach_thread_np(pthread_self())` for earlier versions. But considering it's a fairly early version (wikipedia says its initial release date is August 28, 2009), I don't have a condition to test it. So ignoring this for now until a user reports it.
I ran the 3 …
=> Replace `pthread_self` with `pthread_threadid_np` on macOS

.github/workflows/ci.yml, spdlog/src/formatter/pattern_formatter/pattern/thread_id.rs, spdlog/src/record.rs
Fixes #36.
Currently CI only run `cargo check` for iOS target since `cargo test` needs more effort to configure simulator, and `cargo check` is enough to detect such obvious compilation errors.
@newbeeAirfeeen Can you test this branch on iOS to see if there are any other issues?
=> Handle conditional compilation for getting TID on iOS

spdlog/build.rs
Fixes #40.
In `build.rs`, `generate_code_test_utils` incorrectly instructs `rustc` to rebuild if the generated code is changed, it should be fixed as - rebuild if the read code is changed.
=> Fix rebuild for code generation

spdlog-macros/Cargo.toml, spdlog-macros/src/parse.rs, spdlog-macros/src/synthesis.rs
This PR updates the version of `syn` to 2.0.38. It also resolves various build issues after updating.
This should close #44.
=> Update syn version to 2.0.38

spdlog/src/thread_pool.rs
Following on from discussion in #51, this PR adds two methods to `ThreadPoolBuilder`: `on_thread_spawn` and `on_thread_finish`. These allow for functions to be provided that are called immediately after each pool thread is spawned and immediately before it finishes. 
An example of where these may be useful is for setting core affinity for each thread in the thread pool. This use case inspired the original PR (#51); the implementation in this PR is a completely general interface that also makes this possible.
=> Add methods to provide on spawn and on finish tasks to thread pool builder

spdlog/src/error.rs, spdlog/src/record.rs, spdlog/src/sink/dedup_sink.rs, spdlog/src/sink/mod.rs, spdlog/src/test_utils/common.rs
Introduces a new combined sink that skips consecutive repeated records.
This is the equivalent of [`dup_filter_sink`](https://github.com/gabime/spdlog/blob/0ca574ae168820da0268b3ec7607ca7b33024d05/include/spdlog/sinks/dup_filter_sink.h) in C++ [spdlog](https://github.com/gabime/spdlog).
Sometimes, there will be a lot of duplicate records appearing in the logs, which is a little annoying to the viewers.
With this new sink, more than 2 consecutive repeated records, the records after the first one will be replaced with a single record `"(skipped {count} duplicates)"`.
```rust
install_something(data, |progress| info!("installing... {progress}%"));
```
will produce logs like
```
installing... 0%
installing... 10%
installing... 20%
installing... 20%
installing... 30%
(skipped 10 duplicates) …
```
=> Implement `DedupSink`

spdlog/src/record.rs, spdlog/tests/log_crate_proxy.rs
The `log` crate support specifying log target in the syntax below:
```rust
info!(target: "log-target", "log body");
//    ^~~~~~~~~~~~~~~~~~~~
```
The log target is a string that can be fully customized. Before this PR, this field is not used in spdlog-rs. Actually it can be used as a way to announce the logger name when you want to emit logs in a library through the `log` crate. Thus, in this PR, I used this information as another source of logger names.
Specifically, when constructing a `spdlog::Record` from a `log::Record` with a specific `spdlog::Logger`: (see also [source](https://github.com/Lancern/spdlog-rs/blob/log-target/spdlog/src/record.rs#L123-L154))
- If the `spdlog::Logger` has a logger name configured, the logger name of the constructed `spdlog::Record` will be that name.
- …
=> Add support for log target

spdlog/src/periodic_worker.rs
Fixes #60.
Before this PR, we didn't check the `active` flag if `wait_timeout_while` returns due to a timeout. There may be a small probability issue with this, i.e. `PeriodicWorker` being dropped a short time after the `wait_timeout_while` timeout has returned will potentially result in an infinite join.
=> Check `active` even if `Condvar` times out in `PeriodicWorker`

spdlog/Cargo.toml, spdlog/src/lib.rs, spdlog/src/sink/async_sink/async_pool_sink.rs, spdlog/src/thread_pool.rs, spdlog/tests/global_async_pool_sink.rs
Fixes #64.
I've figured out what happened with this bug. There are 2 things went wrong:
1. `crossbeam` uses thread-local internally, which is not supported in `atexit` callback. This is the reason of panic `use of std::thread::current() is not possible after the thread's local data has been destroyed`.
Fixed it by directly flushing the sinks on the current thread if the program is tearing down.
2. The default logger just gets flushed in `atexit` callback, but not dropped. This results in the program not waiting for the asynchronous thread to finish but simply exiting after the task has been sent.
~Fixed it by changing the global variable with `Option<T>`, so that we could explicitly drop the default logger in `atexit` callback.~ Reverted, paragraph 3 addresses the problem.
3. **UPDATE:** …
=> Flush `AsyncPoolSink` on the current thread if tearing down

spdlog/src/logger.rs, spdlog/src/test_utils/common.rs
=> Implement Debug for Logger

.github/workflows/ci.yml, spdlog/src/record.rs
Fixes #82.
- FreeBSD: https://github.com/gabime/spdlog/blob/f355b3d58f7067eee1706ff3c801c2361011f3d5/include/spdlog/details/os-inl.h#L325-L326
- Illumos: https://github.com/gabime/spdlog/blob/f355b3d58f7067eee1706ff3c801c2361011f3d5/include/spdlog/details/os-inl.h#L331-L332
We don't use `pthread_self` as it returns a opaque pointer, and a pointer value is a little wide for using as an identifier of thread.
---
CC @unknowndevQwQ could you check if this PR works for you?
=> Implement `get_current_tid_inner` for FreeBSD and Illumos

spdlog/Cargo.toml, spdlog/src/lib.rs, spdlog/tests/broken_stdio.rs
Context #87.
Rust's print macros (`{,e}print{,ln}!`) will panic if a write fails. This PR replaces the only use of `eprintln!` with `writeln!(stderr())` to avoid such potential panic.
=> Replace `eprintln!` with `writeln!` to avoid broken stdio panic

.github/workflows/ci.yml, spdlog/src/record.rs
Someone reported an compilation error on Termux in a Telegram Rust group:
```
error[E0425]: cannot find value get_current_tid_inner in this scope
--> /data/data/com.termux/files/home/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/spdlog-rs-0.4.2/src/record.rs:261:57
|
261 | ...ith(get_current_tid_inner))
|        ^^^^^^^^^^^^^^^^^^^^^ not found in this
```
This PR adds supports for Android-like OS.
=> Implement `get_current_tid_inner` for Android

spdlog/Cargo.toml, spdlog/benches/spdlog-rs/pattern.rs, spdlog/examples/05_sink.rs, spdlog/src/env_level.rs, spdlog/src/formatter/local_time_cacher.rs, spdlog/src/logger.rs, spdlog/src/sink/file_sink.rs, spdlog/src/sink/helper.rs, spdlog/src/sink/journald_sink.rs, spdlog/src/sink/rotating_file_sink.rs, spdlog/src/sink/std_stream_sink.rs, spdlog/src/sink/win_debug_sink.rs, spdlog/src/sink/write_sink.rs, spdlog/src/sync.rs
An article I read a long time ago, which was also mentioned by the author of [_spin_](https://crates.io/crates/spin) crate in the README.
[Spinlocks Considered Harmful](https://matklad.github.io/2020/01/02/spinlocks-considered-harmful.html)
Spin locks may offer some advantages in single-threaded scenarios, but they may not perform all that well in multi-threaded, high CPU contention environments.
I previously chose _spin_ because our benchmarks didn't cover high CPU contention scenarios, and IIRC, a few years ago, _spin_ was indeed better than _std_ locks in single-threaded scenarios. But time has moved on, and things may have changed since then, so I opened this PR as a benchmark experiment to compare _spin_, _std_, and _parking_lot_, to see if it's now worth removing _spin_ or even …
=> Replace spin locks with std locks or parking_lot locks
